version: '3.7'
services:
  api:
    container_name: controle_ponto_api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DATABASE_URL: file:./dev.db
    command: yarn start:dev
    ports:
      - '3000:3000'
